language: java
sudo: false
cache:
  directories:
  - "$HOME/.m2"

jdk:
  - oraclejdk8

os:
  - linux

before_deploy:
  - rvm 1.9.3 do gem install octokit -v 4.3.0
  - export DEPLOY_JAR=$(ls target/aloha-*.jar)
deploy:
  provider: releases
  api_key:
    secure: VNhVWrz31Z49AVDibT/x14DLLyNwB20BfuIK7uaZiVAlxeVoF29Knn1anBQZRu1krh5qGB0VG2hZFIz/jzOrVyW0vTH6T1HxrDaFQPwrMY+qmIZtBFl9GFm8lTldl/97GDGns72RX1y6Eu7yjrJVtrayNyYq6FIIIJPslWcdlnLiE8IuBwtzNhNikgVri7dtJLo7VEcdtMRsCsJJMaUwoDbCPCDzUho9qFxbEtYnI68QbEzmXc9uJafKV2Vz0YYV40rhQ/oTg+Q53TE9J4auNNPLMy0jetT1EshpxOYh2PNR5ZUvhnrMqJXaaY8zDr9mBi8Khgt6U2L86ycOOSnK8MNXE7p93Z7Gcv7vZk98KiBUn3YCAQ/zSsDovBp1knVRAoDOvSZzaCVRsXQLWhGQ1Q82fgiPffqFdlHf5mb4ZwzI7EAa3WxhhOHL4AAyzAJOclauLW2pRr04M/6wsUy2vLSYX4Y/zyuoFeBylJqnlcxmYpy5/A+Rr3triNCrY/WE7qNSxV6FRqURUnZLOEHKTxrmWOOwMvX5CGyhgB1MWcxvV0U5B4berLWvxPECOP+8AWULwHiQ8p6FniE85qloTzZUse5ur3/jRAgp/vq5Xt9wUfNVMWgDLn6PDEpyDtEIA5eUaNp8eiR3DjfjR7a2Xn+BbCflQGly8KyG8Bv1/RA=
  file: "${DEPLOY_JAR}"
  on:
    repo: zalora/aloha
    tags: true
