---
infinispan:
  cluster:
    name: Kamehameha
    network.address: 0.0.0.0

  cache:
    name: memcachedCache
    mode: LOCAL
    numOwners: 3 # Amount of machines in the cluster storing the key
    stateTransferChunkSize: 128
    compatibility: true
    lock:
      timeout: 30 # Lock acquisition timeout in seconds
      concurrency: 1024

memcached:
  enabled: false
  host: 0.0.0.0
  port: 11211
  idleTime: -1
  recvBufSize: 0
  sendBufSize: 0
  tcpNoDelay: true

hotrod:
  enabled: true
  topologyLockTimeout: 30000 # ms
  topologyReplTimeout: 30000 # ms

server.port: 8080
logging.level.root: INFO
management.security.enabled: false
endpoints.shutdown.enabled: true
