---
infinispan:
  cluster:
    name: Kamehameha
    statistics.enabled: true
    jgroups.config:

  cache:
    name: memcachedCache
    mode: LOCAL
    numOwners: 3 # Amount of machines in the cluster storing the key
    stateTransferChunkSize: 128
    compatibility: true
    lock:
      timeout: 30 # Lock acquisition timeout in seconds
      concurrency: 1024

memcached:
  host: 0.0.0.0
  idleTime: 2000
  verbose: false
  port:
    primary : 11211
    secondary: 11212

server.port: 8080
logging.level.root: INFO
management.security.enabled: false
endpoints.shutdown.enabled: true
