---
infinispan:
  cluster:
    name: Kamehameha
    statistics.enabled: false
    jgroups.config:

  cache:
    primary:
      name: main
      mode: DIST_SYNC
      enabled: true
      lock:
        timeout: 30 # Lock acquisition timeout in seconds
        concurrency: 1024
      statistics.enabled: true
      l1:
        enabled: true
        lifespan: 600 # lifespan in seconds
      persistence: false # Persists data between reboot
      passivation:
        enabled: true
        dataLocation: diskStore/data/
        expiredLocation: diskStore/expired/
        maxSize: 671_088_640 # If the data uses up more than 640MB, passivation will start

    secondary:
      name: session
      mode: DIST_SYNC
      enabled: false
      statistics.enabled: true
      lock:
        timeout: 30 # Lock acquisition timeout in seconds
        concurrency: 1024
      l1:
        enabled: true
        lifespan: 600 # lifespan in seconds
      passivation:
        enabled: false
        dataLocation: diskStore/secondary/data
        expiredLocation: diskStore/secondary/expired
        maxSize: 10000 # Maximum amount of entries before eviction to disk store starts

    readthrough:
      name: readthrough
      mode: DIST_SYNC
      enabled: false
      preload: false
      preloadPageSize: 5000
      entityClass: com.zalora.aloha.models.entities.Product
      persistenceUnitName: org.infinispan.persistence.jpa
      statistics.enabled: true
      lock:
        timeout: 30 # Lock acquisition timeout in seconds
        concurrency: 1024
      l1:
        enabled: true
        lifespan: 600 # lifespan in seconds

memcached:
  host: 0.0.0.0
  idleTime: 2000
  verbose: false
  port:
    primary : 11211
    secondary: 11212
    readthrough: 11213

spring:
  datasource:
    url:
    username:
    password:
    driver-class-name:
    testWhileIdle: false
    validationQuery:

  jpa:
    show-sql: false
    hbm2ddl-auto: none
    properties.hibernate.dialect:

server.port: 8090
logging.level.root: INFO
management.security.enabled: false
