---
infinispan:
  cluster.name: ElGordo
  cache:
    main:
      name: main
      mode: DIST_ASYNC
      enabled: true
    product:
      name: procuct
      mode: DIST_ASYNC
      enabled: true
    session:
      name: session
      mode: DIST_SYNC
      enabled: true

memcached:
  host: 0.0.0.0
  idleTime: 2000
  verbose: false
  port:
    main: 11211
    product: 11212
    session: 11213

logging.level.root: INFO
